var status = {
  SUCCESS: 200,
  FAILURE_BAD_REQUEST: 400,
  FAILURE_UNAUTHORIZED: 401,
  FAILURE_FORBIDDEN: 403,
  FAILURE_NOT_FOUND: 404,
  FAILURE_CONFLICT: 409,
  FAILURE_TEAPOT: 418,
  FAILURE_INTERNAL: 500
};

module.exports = status;
